### PR TITLE
Fix #6

### LINKED ISSUE #5: Some complex URL are not understood by SciHub with current encode
https://chrome.google.com/webstore/detail/auto-sci-hub/nlogbpfgpkffmombiknfdoogphkimmmd

This is a wonderful tool. But it cannot work in my chrome browser. When I click the extension of 'Auto Sci-hub' at the pape of one paper, the URL of this paper cannot be modified to DOI and hence, this paper cannot be downloaded.

For example, when I click this extension at the page https://www.osapublishing.org/ol/abstract.cfm?uri=ol-37-3-353, I only get this message 'Journal article not found. You can browse or search our database of articles.' However, if I use the DOI of this paper at sci-hub.se, this paper can be downloaded.

So it seems that the URL cannot be modified to DOI by this extension.

### LINKED ISSUE #6: Corrupted SVG makes Chrome install impossible
**Describe the bug**
@Jackymancs4  The SVG is corrupted and Firefox give me some warnings about it and the plugin is impossible to install on chrome because of the SVG file... 

I don't know how it works so can you help me with it? 
The screenshot below is the firefox message (it's not much but it's all what I have) ^^"

**Screenshots**
image

**Desktop (please complete the following information):**
 - Browser Chrome & Firefox
 - Version 1.3

### PR DESCRIPTION
**Pull request by Jackymancs4**
Hello @RoiArthurB 
Here's the fix I promised.

I added png files properly sized for every recommanded resolution.
In the assets folder you can find the original files for inkscape, if you'll want to modify them in the future and exported png version to be used in the store or the README.

But there is a catch.
Since I still think using the pageAction is the right way to go, I had to implement a compatibility trick for Chrome that (as reported here https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction#Browser_compatibility) does not support hide and show match, rendering the icon disabled by default (https://developer.chrome.com/extensions/pageAction).

For reference:
https://stackoverflow.com/questions/9244748/how-do-i-make-page-action-appear-for-specific-pages
Following the implementation of the listener applied to all tabs (that BTW grants great scalability in filtering out domains and websites) I did some major refactoring to the code.

I hope this does not bother you.

This time I extensively tested the extension on both Firefox and Chrome, and the official mozilla linter reported:
```
❯ web-ext lint -s .
Validation Summary:

errors          0
notices         0
warnings        0
```

### CODE REVIEW

**Comment by RoiArthurB** [comment]
In order to stay in a KISS plugin, I think I will use the BrowserAction mode again. But if you want, feel free to fork the app and develop it in Page Action! ^^

Anyway, a huge thanks and a huge bigup to you for all your help ! I hope you had fun doing it 😋

**Comment by Jackymancs4** [comment]
While I disagree for the arguments I exposed in #7 , I'll respect the decision, so no need to fork 👍 

> I hope you had fun doing it 😋

I actually grew quite a disappointment in Chrome architecture, but yes, it's been interesting.

Since I'm at it, I would like to add my last 2cents..

I can be wrong, but you should consider replacing `tabs` permission with `activeTab`
For docs: https://developer.chrome.com/extensions/activeTab and https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#activeTab_permission

This is the weakest permission of them all, and as such the most trustworthy, that still grants all of what you need..

**Comment by RoiArthurB** [comment]
> I can be wrong, but you should consider replacing tabs permission with activeTab

You're absolutly right ! Actually when I created the plugin I search for something similar but I missed it (probably because I missed the correct keyword), but yes, that's an upgrade I want to add!
I'll work on it now, thanks again for your ressources ^^

And FWI the version 1.4 (with your last merge and my modifications) is live on both browser, you can update it and see your beautiful icon set live 😄

**Comment by Jackymancs4** [comment]
Once again Open Source won 👍🏻 Have a great day!

**Pull request merged**
